/*
 * File: app/view/MainFramework.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Weblushi.view.MainFramework', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'border'
    },
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    id:'contentTabPanel',
                    region: 'center',
                    split: false,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: '主页'
                        }/*,
                        {  
                            id: "tab1",  
                            layout:'fit',
                            title: '普通Tab',  
                            html: "这只是一个非常普通的Tab。",  
                            items:  Ext.create('Weblushi.view.ServiceTemplateManage'),  
                            closable: true                  
                        },
                        {  
                            id: "tab2",  
                            layout:'fit',
                            title: '普通Tab',  
                            html: "这只是一个非常普通的Tab。",  
                            items:  Ext.create('Weblushi.view.ServiceCategoryManage'),  
                            closable: true                  
                        },
                        {  
                            id: "tab3",  
                            layout:'fit',
                            title: '普通Tab',  
                            items:  Ext.create('Weblushi.view.ServiceManage')
                        }*/
                        
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 60,
                    layout: {
                        align: 'stretch',
                        padding: '5px',
                        type: 'vbox'
                    },
                    title: '',
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            items: [
                                {
                                    xtype: 'label',
                                    text: '管理系统'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 0,
                            layout: {
                                align: 'stretch',
                                pack: 'end',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    border:false,
                                    //text: '',
                                    html:''
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'treepanel',
                    id:'menuTreePanel',
                    region: 'west',
                    split: true,
                    width: 240,
                    title: '菜单',
                    root:{
                        text: "菜单",
                        expanded: true,
                        children: [
                            { text: "请求管理", tabId:'tab1',clazz:'MedicalProject.view.RequestManage' ,leaf: true },
                            { text: "用户管理", tabId:'tab2',clazz:'MedicalProject.view.UserManage',leaf: true },
                            { text: "资格申请管理", tabId:'tab3',clazz:'MedicalProject.view.QualificationApplicationManage',leaf: true },
                            { text: "交易管理", tabId:'tab4',clazz:'MedicalProject.view.TransactionManage',leaf: true }
                        ]
                    },
                    viewConfig: {

                    },
                    columns: [
                          {
                              xtype: 'treecolumn',
                              width: 167,
                              dataIndex: 'text',
                              text: '菜单名称',
                              flex: 1
                          }/*,
                          {
                              xtype: 'gridcolumn',
                              dataIndex: 'menuDesc',
                              text: '菜单描述'
                          }*/
                      ]
                }
            ]
        });

        me.callParent(arguments);
        
        me.bindEvent();
        
        me.init();
    },
    bindEvent:function(){
    	var me = this;
    	Ext.getCmp('menuTreePanel').on('itemclick',function($this,rec){
    		var tabId = rec.raw.tabId;
    		var text = rec.data.text;
    		var clazz = rec.raw.clazz;
			me.openTab(tabId,text,clazz);
    	});
    },
    openTab:function(tabId,text,clazz){
    	var me = this;
    	var contentTabPanel = Ext.getCmp('contentTabPanel');
    	var tab = Ext.getCmp(tabId);
    	if( tab ){
    		contentTabPanel.setActiveTab(tab);
    	}else{
        	tab = contentTabPanel.add({
    	    		id: tabId,  
    	            layout:'fit',
    	            title: text,  
    	            items:  Ext.create(clazz),  
    	            closable: true        
        		});
        	contentTabPanel.setActiveTab(tab);
    	}
    },
    init:function(){
    	
    }

});