/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
var serviceCateComboStore = Ext.create('Ext.data.Store',{
	fields: ['id', 'cateName'],
    autoLoad: true,
    //url: 'test.php',
    proxy: {
    	type: 'ajax',
        url: appContext + '/admin/service/listAllServiceCategory.do',
        reader: {
            root: 'data',
            totalProperty: 'totalCount'
        }
    }
});

var templateComboStore = Ext.create('Ext.data.Store',{
	fields: ['id', 'templateName'],
    autoLoad: true,
    //url: 'test.php',
    proxy: {
    	type: 'ajax',
        url: appContext + '/admin/service/listAllServiceTemplate.do',
        reader: {
            root: 'data',
            totalProperty: 'totalCount'
        }
    }
});

Ext.define('Weblushi.view.PublishServiceWin', {
    extend: 'Ext.window.Window',

    height: 280,
    width: 491,
    layout: {
        type: 'fit'
    },
    title: '发布服务',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    id:'publishServiceWin_publishServiceForm',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'anchor'
                            },
                            items: [
								{
								    xtype: 'hidden',
								    name:'contactUserId'
								},
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: '名称',
                                    name:'serviceName'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: '类型',
                                    name:'serviceCategoryId',
                                    mode: 'remote',
                                    valueField: 'id',
                                    displayField: 'cateName',
                                    store:serviceCateComboStore
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    fieldLabel: '描述',
                                    name:'serviceDesc'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: '价格',
                                    name:'servicePrice'
                                },
                                {
                                    xtype: 'combobox',
                                    name:'templateId',
                                    anchor: '100%',
                                    fieldLabel: '模板',
                                    mode: 'remote',
                                    valueField: 'id',
                                    displayField: 'templateName',
                                    store: templateComboStore
                                },
                                {
                                    xtype: 'trigger',
                                    id:'publishServiceWin_contactUserTrigger',
                                    anchor: '100%',
                                    fieldLabel: '联系人',
                                    name:'contactUserName',
                                    onTriggerClick:me.onContactUserTriggerClick,
                                    submitValue:false
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 0,
                            layout: {
                                align: 'stretch',
                                pack: 'center',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    id:'publishServiceWin_publishBtn',
                                    width: 80,
                                    text: '发布'
                                },
                                {
                                    xtype: 'button',
                                    id:'publishServiceWin_cancelBtn',
                                    width: 80,
                                    text: '取消'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
        
        me.bindEvent();
        
        me.init();
    },
    init:function(){
    	
    },
    bindEvent :function(){
    	var me = this;
    	var publishBtn = Ext.getCmp('publishServiceWin_publishBtn');
    	var cancelBtn = Ext.getCmp('publishServiceWin_cancelBtn');
    	var publishServiceForm = Ext.getCmp('publishServiceWin_publishServiceForm');
    	var contactUserTrigger = Ext.getCmp('publishServiceWin_contactUserTrigger');
    	
    	publishBtn.on('click',function(){
    		publishServiceForm.getForm().submit({
        	    clientValidation: true,
        	    url:  appContext + '/admin/service/publishService.do',
        	    params: {
        	    },
        	    success: function(form, action) {
        	    	publishServiceForm.getForm().reset();
        	       
        	    	me.done();
        	    	me.close();
        	    },
        	    failure: function(form, action) {
        	        Ext.Msg.alert('失败', action.result.msg);
        	    }
        	});
    	});
    	
    	cancelBtn.on('click',function(){
    		me.close();
    	});
    	
    },
    onContactUserTriggerClick: function(){
    	Ext.create(
			'Weblushi.view.SelectUserWin',
			{
				modal :true,
				done: function(user){
					console.log(user);
				}
			}
		).show();
    }

});