/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */


    
var userGridStore = Ext.create('Ext.data.Store', {
	extend: 'Ext.data.Store',
    
    fields: ['serviceId','serviceName','serviceDesc','serviceCategoryId','serviceCategory','servicePrice','createTime',
             'createTimeUtime','contactUserId','contactUserName','publishUserId','publishUserName','templateId','templateName'],
    autoLoad: true,
    //pageSize: 10,
    proxy: {
        type: 'ajax',
        url : appContext + '/admin/service/listServiceByCond.do',
        //actionMethods: { read: 'POST' }  ,	
        pageParam:"page", 
        limitParam:"pageSize",
        reader: {
            type: 'json',
            root: 'data.serviceList',
            totalProperty: 'data.pager.totalCount'
        }
    }
});

Ext.define('MedicalProject.view.UserManage', {
    extend: 'Ext.container.Container',

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 0,
                            layout: {
                                columns: 4,
                                type: 'table'
                            },
                            bodyPadding: 10,
                            title: '服务管理',
                            items: [
                                {
                                    xtype: 'datefield',
                                    fieldLabel: '发布时间'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 5px',
                                    fieldLabel: '服务名称'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 5px',
                                    fieldLabel: '状态'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 5px',
                                    width: 80,
                                    text: '搜索'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            id:'userManage_userGrid',
                            store: userGridStore,
                            flex: 1,
                            title: '服务列表',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'createTime',
                                    text: '发布时间'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'serviceName',
                                    text: '服务名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'serviceCategory',
                                    text: '分类'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'servicePrice',
                                    text: '服务价格'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 108,
                                    dataIndex: 'publishUserName',
                                    text: '发布者'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'contactUserName',
                                    text: '联系人'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'templateName',
                                    text: '模板'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true,
                                    store:serviceGridStore
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: '新建服务',
                                            id: 'serviceManage_tbCreateServiceBtn'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'button',
                                            text: '禁用服务'
                                        }/*,
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'splitbutton',
                                            text: '人员分配',
                                            menu: {
                                                xtype: 'menu',
                                                items: [
                                                    {
                                                        xtype: 'menuitem',
                                                        text: '分配导师'
                                                    },
                                                    {
                                                        xtype: 'menuitem',
                                                        text: '分配审查员'
                                                    }
                                                ]
                                            }
                                        }*/
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
        //me.bindEvent();
       // me.init();
    },
    init : function(){
    	var me = this;
    	var serviceGrid = Ext.getCmp('serviceManage_serviceGrid');
    	
    	/*serviceGrid.getStore.load({
    		params:{
    			page:1
    		}
    	});*/
    },
    bindEvent: function(){
    	var me = this;
    	var serviceGrid = Ext.getCmp('userManage_userGrid');
    	Ext.getCmp('serviceManage_tbCreateServiceBtn').on('click',function(){
    		Ext.create(
				'Weblushi.view.PublishServiceWin',
				{
					modal :true,
					done: function(){
						serviceGrid.getStore().reload();
					}
				}
    		).show();
    	});
    }

});